# for each folder in anda/
# generate a new workflow for each folder in anda/
name: Automatically build packages
on:
  push:
    paths:
      - anda/**
    branches:
      - el10
  pull_request:
    branches:
      - el10
  merge_group:
    branches:
      - el10
  workflow_dispatch:
  workflow_call:

jobs:
  manifest:
    runs-on: ubuntu-latest

    outputs:
      build_matrix: ${{ steps.generate_build_matrix.outputs.build_matrix }}
    container:
      image: ghcr.io/terrapkg/builder:el10
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Set workspace as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate build matrix
        id: generate_build_matrix
        run: anda ci >> $GITHUB_OUTPUT
  build:
    needs: manifest
    strategy:
      matrix:
        pkg: ${{ fromJson(needs.manifest.outputs.build_matrix) }}
        version: ["10"]
      fail-fast: false
    runs-on: ${{ (matrix.pkg.arch == 'aarch64' && matrix.pkg.labels['large']) && 'arm64-lg' || matrix.pkg.arch == 'aarch64' && 'ubuntu-22.04-arm' || matrix.pkg.labels['large'] && 'x86-64-lg' || 'ubuntu-22.04' }}
    container:
      image: ghcr.io/terrapkg/builder:el${{ matrix.version }}
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout latest Mock configs
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: terrapkg/mock-configs
          path: mock-configs

      - name: Set up git repository
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Include custom build template instead of package default
        run: |
          cp -v mock-configs/terra-el.tpl /etc/mock/templates/
          cp -v mock-configs/terra-el-dev.tpl /etc/mock/templates/

      - name: Build with Andaman
        run: |
          dnf builddep -y `echo ${{ matrix.pkg.pkg }} | sed -E 's@/pkg$@/*.spec@'`
          anda build ${{ matrix.pkg.pkg }} -rrpmbuild

      - name: Generating artifact name
        id: art
        run: |
          NAME=${{ matrix.pkg.pkg }}-${{ matrix.pkg.arch }}-${{ matrix.version }}
          x=${NAME//\//@}
          echo "name=$x" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.art.outputs.name }}
          compression-level: 0 # The RPMs are already compressed :p
          path: |
            anda-build/rpm/rpms/*
            anda-build/rpm/srpm/*

      - name: Upload packages to subatomic
        if: github.event_name == 'push'
        run: |
          subatomic-cli upload --prune \
            --server https://subatomic.fyralabs.com \
            --token ${{ secrets.SUBATOMIC_TOKEN }} \
            terrael${{ matrix.version }} anda-build/rpm/rpms/*

      - name: Upload source packages to subatomic
        if: github.event_name == 'push'
        run: |
          subatomic-cli upload --prune \
            --server https://subatomic.fyralabs.com \
            --token ${{ secrets.SUBATOMIC_TOKEN }} \
            terrael${{ matrix.version }}-source anda-build/rpm/srpm/*

      - name: Notify Madoguchi (Success)
        if: success() && github.event_name == 'push'
        run: ./.github/workflows/mg.sh true ${{matrix.pkg.pkg}} ${{matrix.version}} ${{matrix.pkg.arch}} ${{github.run_id}} ${{secrets.MADOGUCHI_JWT}} $GITHUB_SHA
      - name: Notify Madoguchi (Failure)
        if: ( cancelled() || failure() ) && github.event_name == 'push'
        run: ./.github/workflows/mg.sh false ${{matrix.pkg.pkg}} ${{matrix.version}} ${{matrix.pkg.arch}} ${{github.run_id}} ${{secrets.MADOGUCHI_JWT}} $GITHUB_SHA
